# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d95c8ecbb97477942bda1bc7a09b3ca5c0f1305c76281500bf6e724c64ef14f908f5dd2d6e96a914aa367afc31432d2c6e83d17a2ebb43ab7efd6a3f1e980b4

test:
  secret_key_base: 064ded411ba0461ae750c8c1d38255c8a87af22e801e1f29d3a92212f2a89dbc4ad27dd968818745db50a6ac54d03ae9c08558cf1ef1f6a5b8312a754411149a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
